---
title: "EPI 590R Final Project"
author: "Cassie York"
format: html
editor: visual
---

## Background

This data set contains data from PCR testing for COVID-19 during 2020 at the Children's Hospital of Pennsylvania. Amrom E. Obstfeld deidentified this data set through anonymizition, time-shifting, and permution.

```{r}
#| echo: false
#| include: false
#| warning: false

remotes::install_github("higgi13425/medicaldata")
library(tidyverse)
library(gtsummary)
library(medicaldata)

covid <- medicaldata::covid_testing %>%
	mutate(result = factor(result, labels = c("Invalid", "Negative", "Positive")),
				 demo_group = factor(demo_group, labels = c("Client", "Misc Adult", "Other Adult", "Patient", "Unidentified")),
				 gender = factor(gender, labels = c("Female", "Male")))

```

```{r}
#| echo: false
#| warning: false
#| label: tbl-one
#| tbl-cap: "Descriptive Statistics"

tbl_summary(
  covid,
  by = gender,
  include = c(age, demo_group, result, drive_thru_ind, pan_day, col_rec_tat),
  label = list(
  	age ~ "Age (Years)",
  	demo_group ~ "Type of Subject",
  	result ~ "COVID Test Result",
  	drive_thru_ind ~ "Specimen Collected via Drive-Thru Site",
  	pan_day ~ "Day After Start of Pandemic in Which Specimen Was Collected (Days)",
  	col_rec_tat ~ "Time Elapsed Between Collect Time and Receive Time (Hours)")) %>%
  add_overall() %>% 
  bold_labels() %>% 
  modify_footnote(update = everything() ~ NA) %>% 
  modify_header(label = "**Variable**")
```

```{r}
#| echo: false
#| label: tbl-two
#| tbl-cap: "Logistic Regression Results"

tbl_uvregression(
  covid, 
  y = result,
  include = c(age, demo_group, result, drive_thru_ind, pan_day, col_rec_tat),
  label = list(
  	age ~ "Age (Years)",
  	demo_group ~ "Type of Subject",
  	result ~ "COVID Test Result",
  	drive_thru_ind ~ "Specimen Collected via Drive-Thru Site",
  	pan_day ~ "Day After Start of Pandemic in Which Specimen Was Collected (Days)",
  	col_rec_tat ~ "Time Elapsed Between Collect Time and Receive Time (Hours)"),
  method = glm,
  method.args = list(family = binomial()),
  exponentiate = TRUE) %>%
	bold_labels() %>% 
  modify_footnote(update = everything() ~ NA)
```

```{r}
#| echo: false
#| message: false
#| label: fig-one
#| fig-cap: "Test Result Count by Gender"

barplot <- covid %>%
	ggplot(aes(x = result, fill = gender)) +
	geom_bar(position = "dodge") +
	labs(x = "Test Result", y = "Count") +
	scale_fill_discrete(name = "Gender")

print(barplot)

ggsave(plot = barplot,
			 filename = here::here("figures/barplot.pdf"))
```

```{r}
#| echo: false


```

